
// File generated by darts version 12.1.55, Wed Feb 26 00:16:30 2014
// Copyright(c) 1996-2012 Target Compiler Technologies NV
// All rights reserved.
// C:\Program Files\Target Compiler Technologies\yecore-12R1\bin\WINbin\darts.exe -B +F -IC:/Program Files/Target Compiler Technologies/yecore-12R1/designs/yecore/lib +p -d -h -Iinclude -Imain -I../../../IP Designer/lib -IC:/Program Files/Target Compiler Technologies/yecore-12R1/designs/yecore/lib/runtime/include -D__tct_patch__=6 -p +r +Ihex Release/Global.o yecore

// Release: yecore 12R1.6
.data_segment_name
.bss global 2 AxisHdl PREG 1280

.data_segment_name
.bss global 2 AxisNum PREG 2

.data_segment_name
.bss global 1 ZERO PREG 1

.data_segment_name
.bss global 1 ONE PREG 1

.data_segment_name
.bss global 2 True PREG 2

.data_segment_name
.bss global 2 False PREG 2

.data_segment_name
.bss global 1 VerInfo PREG 4

.undef global data NumberOfAxes

